import Ajv from 'ajv/dist/2020.js';
import standalone from 'ajv/dist/standalone/index.js';
import { readFile, writeFile } from 'node:fs/promises';
const ajv = new Ajv({code:{source:true,esm:true},allErrors:true,strict:true});
const schema = JSON.parse(await readFile('config/scan.schema.json','utf8'));
const generated=standalone(ajv,ajv.compile(schema)).replace(/const (\w+) = require\("(ajv\/dist\/runtime\/[^"]+)"\)\.default;/g, (_match,name,path) => `import ${name} from '${path}.js';`);
await writeFile('src/generated/selection.js', '// Generated by scripts/generate-schema.mjs; edit config/scan.schema.json.\n'+generated);
